services:
  amarillo:
    image: "git.gerhardt.io/amarillo/amarillo:latest"
    environment:
    # Configure these for external enhancer and/or generator
    - ENHANCER_URL=${AMARILLO_ENHANCER_URL:-http://enhancer:80} 
    - GENERATOR_URL=${AMARILLO_GENERATOR_URL:-http://generator:80} 

    - ADMIN_TOKEN=${ADMIN_TOKEN?}
    - RIDE2GO_TOKEN=${RIDE2GO_TOKEN-}
    - GRAPHHOPPER_BASE_URL='https://api.mfdz.de/gh'
    - SECRET_KEY=${SECRET_KEY?}
    - METRICS_USER=${METRICS_USER?}
    - METRICS_PASSWORD=${METRICS_PASSWORD?}
    
    - MAX_WORKERS=${MAX_WORKERS}
    volumes:
    - ./data:/app/data
    ports:
      - "${PORT:-8000}:80"
  enhancer:
    image: ${AMARILLO_ENHANCER_IMAGE:-"git.gerhardt.io/amarillo/amarillo-enhancer:latest"}
    volumes:
    - ./data:/app/data
    profiles:
      - enhancer
  generator:
    image: ${AMARILLO_GENERATOR_IMAGE:-"git.gerhardt.io/amarillo/amarillo-gtfs-generator:latest"}
    volumes:
    - ./data:/app/data
    profiles:
      - generator


#sudo docker compose --profile enhancer up   
#sudo docker compose --profile generator up   
#sudo docker compose --profile enhancer --profile generator up   